### ISSUE TITLE
Product list is often not shown when it should be

### ISSUE THREAD

**Issue by david-r-edgar** [projectwife/mtesitoo-android#48] opened 2016-12-07 16:18 UTC
I add a new product.
I view the summary and submit. The screen is now blank.
How do I get back to the list of products? On load it normally appears here after a short delay.

This also happens in other circumstances - I click 'Home' and all I see is a blank screen. There's no loading indicator, so I don't know whether it's failing to load the product list, or whether it isn't even trying to load it.

**Comment by carlpoole** [comment] 2016-12-11 19:34
Confirmed, it looks like it might have something to do with the "Pending Approval" status in opencart. I added Corn to my products just now and it didnt show for a moment. Then after a change it has disappeared again. It looks like it isnt being returned in the API call http://104.155.84.193/api/v1/product/vendor/23/products

**Comment by carlpoole** [comment] 2017-01-01 14:17
Looks like this is API related, corn is returning now after approval. Is this something that needs to be fixed on your end @david-r-edgar or is that expected behavior?

**Comment by david-r-edgar** [comment] 2017-01-01 15:04
I don't think this is an API related thing.

Whether the recent product is shown or not is not really the problem.

The vendor already had many products listed. They add a new product. Then all the existing products should be shown (maybe or maybe not including the recent product). When the problem happens, the screen is completely blank - none of the products are shown at all.

**Comment by carlpoole** [comment] 2017-01-01 15:06
Oh okay, sorry misread. Didn't realize the whole screen wasn't loading correctly. Will try to reproduce this one

**Comment by CraigBanach** [comment] 2017-02-05 13:46
Fixed in pull request 66.

**Comment by CraigBanach** [comment] 2017-02-05 17:29
Added ProgressDialog to productlist screen. Not 100% that this will fix it, but I think it will.

**Closed by CraigBanach** 2017-02-05 17:29 UTC
Labels: bug
