### ISSUE TITLE
'orders' never becomes un-highlighted in menu

### ISSUE THREAD

**Issue by david-r-edgar** [projectwife/mtesitoo-android#14] opened 2016-08-28 17:01 UTC
On first login, 'home' is selected in the menu. After I select 'orders', it's highlighted. If I select anything else, 'orders' remains highlighted. This is not correct.

**Comment by kaizen10** [comment] 2016-10-31 22:53
This can be duplicated with most of the menu items (e.g. info, profile, ...). The problem is that many of the menu item do not become selected when clicked. I'll submit a fix for this tomorrow.

**Comment by kaizen10** [comment] 2016-10-31 23:29
Fixed.

**Closed by kaizen10** 2016-10-31 23:29 UTC
Labels: bug
