### ISSUE TITLE
Add new product - Category list is list of Countries 

### ISSUE THREAD

**Issue by gwenpowers** [projectwife/mtesitoo-android#118] opened 2017-07-02 12:12 UTC

**Comment by ptyagicodecamp** [comment] 2017-07-06 18:38
Can you provide more details about the build version. I don't see this happening on latest play store build. A screenshot will be helpful.

**Comment by david-r-edgar** [comment] 2017-07-06 20:48
The related (but opposite) issue (#60) didn't happen every time, just occasionally. It was never properly fixed, just removed.
I wonder whether they have the same origin? A shared list object or something, which isn't properly updated?
Would code review of the relevant code paths find this faster than attempting to reproduce it manually?

**Comment by ptyagicodecamp** [comment] 2017-07-06 21:41
@david-r-edgar sounds good to me. will do a code walkthrough.

**Comment by ptyagicodecamp** [comment] 2017-07-16 06:42
I checked the latest code responsible for [adding a new Product](https://github.com/projectwife/mtesitoo-android/blob/master/app/src/main/java/com/mtesitoo/AddProductActivity2.java). I see all the references to `Category` and none to `Country`.

**Comment by ptyagicodecamp** [comment] 2017-07-21 06:26
I'm closing since I didn't see any apparent issues in code walk through.

**Comment by david-r-edgar** [comment] 2017-07-21 06:43
Sorry, can I keep this open... was meaning to look more into it. I found something suspicious the other day, will look more into it first.

**Comment by ptyagicodecamp** [comment] 2017-07-21 06:48
@david-r-edgar Sure ! Let me know how can I help.
The new class responsible for adding product [AddProductActivity2](https://github.com/projectwife/mtesitoo-android/blob/master/app/src/main/java/com/mtesitoo/AddProductActivity2.java) doesn't seem to have any references to country listing.

**Closed** 2017-07-21 21:46 UTC
